//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/cm_arena.html
halflife.wad
liquids.wad
sprites/glow01.spr
sound/ambience/drips.wav
sprites/e-tele1.spr
sound/ambience/alien_beacon.wav
sound/debris/beamstart1.wav
sprites/xsmoke1.spr
sound/ambience/techamb2.wav
gfx/env/desbk.tga
gfx/env/desdn.tga
gfx/env/desft.tga
gfx/env/deslf.tga
gfx/env/desrt.tga
gfx/env/desup.tga
sprites/hotglow.spr
sound/ambience/steamjet1.wav
sound/ambience/techamb1.wav
sound/ambience/alien_creeper.wav
sound/scientist/scream24.wav
sound/ambience/alien_builder.wav
sprites/nhth1.spr
sprites/c-tele1.spr
sound/fans/fan5.wav
maps/cm_arena.bsp
maps/cm_arena.txt
