//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/valve/crossfire_upgrade.html
halflife.wad
xeno.wad
sprites/glow01.spr
sound/rings2.wav
sound/rings1.wav
sound/weapons/sbarrel1.wav
sound/ambience/jetflyby1.wav
sound/weapons/mortarhit.wav
sound/debris/beamstart11.wav
sound/weapons/electro5.wav
sprites/steam1.spr
sprites/muzzleflash1.spr
sound/ambience/alarm_main.wav
maps/crossfire_upgrade.bsp
